export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as TravelType } from "./TravelType";
export { default as SeparatorWithText } from "./SeparatorWithText";
export { default as BlogSlider } from "./BlogSlider";
export { default as TourContent } from "./TourContent";
export { default as TourHeading } from "./TourHeading";
export { default as Itinerary } from "./Itinerary";
export { default as TourHero } from "./TourHero";
export { default as TourSideBar } from "./TourSideBar";
export { default as Progress } from "./Progress";
export { default as SkipAndNext } from "./SkipAndNext";
export { default as Hotels } from "./Hotels";
export { default as Ticket } from "./Ticket";
export { default as Culture } from "./Culture";
export { default as Books } from "./Books";
export { default as DestinationDetailsFinal } from "./DestinationDetailsFinal";
export { default as PaymentForm } from "./PaymentForm";

